/**
 * @deprecated This mock data is no longer used by the dashboard.
 * The dashboard now fetches real data from Supabase via gameRoomService.
 */
export const GAME_ROOMS = [
  // Pemrograman Category
  {
    game_room_id: "1",
    room_code: "123456",
    topic_material: "Pemrograman Dasar",
    category: "Pemrograman",
    max_player: 25,
    usersRegistered: 17,
    total_question: 20,
    total_round: 5,
    difficulty: "mudah",
    image_url: "/quiz-category/pemrograman.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p1",
        name: "Slimey",
        character: "Slime",
        image: "/default/Slime.webp",
      },
      {
        id: "p2",
        name: "Griffin",
        character: "Griffin",
        image: "/default/Griffin.webp",
      },
      { id: "p3", name: "Blaze", character: "Api", image: "/default/Api.webp" },
      {
        id: "p4",
        name: "Phoenix",
        character: "Phoenix",
        image: "/default/Phoenix.webp",
      },
    ],
  },
  {
    game_room_id: "2",
    room_code: "654321",
    topic_material: "Javascript",
    category: "Pemrograman",
    max_player: 25,
    usersRegistered: 10,
    total_question: 20,
    total_round: 5,
    difficulty: "mudah",
    image_url: "/quiz-category/pemrograman.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      { id: "p5", name: "Aqua", character: "Air", image: "/default/Air.webp" },
      {
        id: "p6",
        name: "Robo",
        character: "Robot",
        image: "/default/Robot.webp",
      },
      {
        id: "p7",
        name: "Ghost",
        character: "Hantu",
        image: "/default/Hantu.webp",
      },
      {
        id: "p8",
        name: "Yeti",
        character: "Yeti",
        image: "/default/Yeti.webp",
      },
    ],
  },
  {
    game_room_id: "3",
    room_code: "112233",
    topic_material: "Struktur Data",
    category: "Pemrograman",
    max_player: 25,
    usersRegistered: 5,
    total_question: 15,
    total_round: 3,
    difficulty: "sedang",
    image_url: "/quiz-category/pemrograman.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p9",
        name: "Vamp",
        character: "Vampir",
        image: "/default/Vampir.webp",
      },
      {
        id: "p10",
        name: "Alien",
        character: "Alien",
        image: "/default/Alien.webp",
      },
      {
        id: "p11",
        name: "Dragon",
        character: "Naga",
        image: "/default/Naga.webp",
      },
      {
        id: "p12",
        name: "Shroom",
        character: "Jamur",
        image: "/default/Jamur.webp",
      },
    ],
  },
  {
    game_room_id: "4",
    room_code: "445566",
    topic_material: "Pemrograman Lanjut",
    category: "Pemrograman",
    max_player: 25,
    usersRegistered: 3,
    total_question: 25,
    total_round: 5,
    difficulty: "sulit",
    image_url: "/quiz-category/pemrograman.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p13",
        name: "Slime Elite",
        character: "Juragan Slime",
        image: "/epic/Juragan%20Slime.webp",
      },
      {
        id: "p14",
        name: "Batik AI",
        character: "Cyber Batik",
        image: "/epic/Cyber%20Batik.webp",
      },
      {
        id: "p15",
        name: "Fire Soul",
        character: "Api Baskara",
        image: "/epic/Api%20Baskara.webp",
      },
    ],
  },
  // Biologi Category
  {
    game_room_id: "5",
    room_code: "998877",
    topic_material: "Sistem Pencernaan",
    category: "Biologi",
    max_player: 25,
    usersRegistered: 17,
    total_question: 20,
    total_round: 5,
    difficulty: "mudah",
    image_url: "/quiz-category/biologi.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p16",
        name: "Sky Rider",
        character: "Mega Mendung",
        image: "/epic/Mega%20Mendung.webp",
      },
      {
        id: "p17",
        name: "Stone",
        character: "Batu Pendekar",
        image: "/epic/Batu%20Pendekar.webp",
      },
      {
        id: "p18",
        name: "Ghost King",
        character: "Jurig Peci",
        image: "/epic/Jurig%20Peci.webp",
      },
      {
        id: "p19",
        name: "Wolf",
        character: "Roger Malam",
        image: "/epic/Roger%20Malam.webp",
      },
    ],
  },
  {
    game_room_id: "6",
    room_code: "111222",
    topic_material: "Bioteknologi",
    category: "Biologi",
    max_player: 25,
    usersRegistered: 10,
    total_question: 20,
    total_round: 5,
    difficulty: "sedang",
    image_url: "/quiz-category/biologi.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p20",
        name: "Mecha Blaze",
        character: "Mecha Blaze",
        image: "/legend/Mecha%20Blaze.webp",
      },
      {
        id: "p21",
        name: "Akuatron",
        character: "Akuatron",
        image: "/legend/Akuatron.webp",
      },
      {
        id: "p22",
        name: "Srikandi",
        character: "Srikandi",
        image: "/epic/Srikandi.webp",
      },
      {
        id: "p23",
        name: "Peri",
        character: "Peri Jelita",
        image: "/epic/Peri%20Jelita.webp",
      },
    ],
  },
  {
    game_room_id: "7",
    room_code: "333444",
    topic_material: "Virus",
    category: "Biologi",
    max_player: 25,
    usersRegistered: 5,
    total_question: 20,
    total_round: 5,
    difficulty: "sedang",
    image_url: "/quiz-category/biologi.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p24",
        name: "Unicorn",
        character: "Kuda Kencana",
        image: "/epic/Kuda%20Kencana.webp",
      },
      {
        id: "p25",
        name: "Vampir",
        character: "Raden Drakula",
        image: "/epic/Raden%20Drakula.webp",
      },
      {
        id: "p26",
        name: "Yeti Sage",
        character: "Yeti Petapa",
        image: "/epic/Yeti%20Petapa.webp",
      },
      {
        id: "p27",
        name: "Gold Phoenix",
        character: "Phoenix",
        image: "/default/Phoenix.webp",
      },
    ],
  },
  {
    game_room_id: "8",
    room_code: "555666",
    topic_material: "Jamur",
    category: "Biologi",
    max_player: 25,
    usersRegistered: 3,
    total_question: 20,
    total_round: 5,
    difficulty: "sedang",
    image_url: "/quiz-category/biologi.webp",
    room_status: "open",
    room_visibility: "public",
    players: [
      {
        id: "p28",
        name: "Slimey",
        character: "Slime",
        image: "/default/Slime.webp",
      },
      {
        id: "p29",
        name: "Griffin",
        character: "Griffin",
        image: "/default/Griffin.webp",
      },
      {
        id: "p30",
        name: "Blaze",
        character: "Api",
        image: "/default/Api.webp",
      },
    ],
  },
];
